application: puppy-runner
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /font
  static_dir: static/font

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /.*
  script: plantilla.app
